const data = [
  {
    category: "Official / Governance / Metrics",
    icon: "./icons/official.png",
    links: [
      {
        name: "algorand",
        url: "https://algorand.co/",
        tags: [
          "Official",
          "algorand",
          "technologies",
          "inc",
          "algorand foundation",
          "developers",
          "resources",
          "community",
        ],
      },
      {
        name: "algorandtechnologies",
        url: "https://algorandtechnologies.com/",
        tags: ["Official", "inc"],
      },
      {
        name: "Governance Portal",
        url: "https://governance.algorand.foundation/",
        tags: ["dapps", "algorand", "Official"],
      },
      {
        name: "algorand - metrics",
        url: "https://algorand.co/metrics",
        tags: [
          "Governance",
          "Official",
          "Algorand Metrics",
          "metrics.algorand.org",
        ],
      },
      {
        name: "Xgov",
        url: "https://xgov.algorand.foundation/",
        tags: [
          "dapps",
          "algorand",
          "Official",
          "Xgov",
          "voting",
          "stats",
          "Foundation",
          "Governance",
          "Algorand",
        ],
      },
      {
        name: "Xgov-viewer",
        url: "https://xgov-viewer.netlify.app/",
        tags: ["Xgov", "Guru", "Governance", "Algorand"],
      },
      {
        name: "allo.info",
        url: "https://metrics.allo.info/",
        tags: ["Governance", "Algorand", "Metrics"],
      },
      {
        name: "Nodely",
        url: "https://g.nodely.io/d/tps/mainnet?orgId=1&refresh=5s",
        tags: ["Algorand Metrics TPS"],
      },
      {
        name: "fiatleak",
        url: "https://fiatleak.com/algo",
        tags: ["fiatleak"],
      },
      {
        name: "nansen",
        url: "https://app.nansen.ai/macro/blockchains?chain=algorand",
        tags: ["Algorand Metrics"],
      },
    ],
  },

  {
    category: "FAQs",
    icon: "./icons/faq.png",
    links: [
      {
        name: "Can a blockchain do that?",
        url: "https://canablockchaindothat.com/",
        tags: [
          "FAQs",
          "algorand",
          "Official",
          "Can a blockchain do that?",
          "Use cases from the real world",
        ],
      },
      {
        name: "Technology FAQ",
        url: "https://www.algorand.com/technology/faq",
        tags: ["FAQs", "algorand", "Official"],
      },
      {
        name: "Governance FAQ",
        url: "https://algorand.co/FAQs",
        tags: ["FAQs", "algorand foundation", "Official"],
      },
      {
        name: "Node Staking FAQ",
        url: "https://algorand.co/staking-rewards",
        tags: [
          "FAQs",
          "algorand foundation",
          "Official",
          "Staking",
          "NODE",
          "yield farming",
          "Consensus",
        ],
      },
      {
        name: "Unofficial FAQ",
        url: "https://github.com/HashMapsData2Value/AlgorandFAQ/blob/main/README.md",
        tags: ["FAQs", "algorand"],
      },
    ],
  },
  {
    category: "Blockchain Explorers",
    icon: "./icons/explorer.png",
    links: [
      {
        name: "Pera Explorer",
        url: "https://explorer.perawallet.app/",
        tags: ["algorand", "Blockchain Explorers", "Infrastructure"],
      },
      {
        name: "chaintrail",
        url: "https://chaintrail.io/",
        tags: ["algorand", "Blockchain Explorers", "Infrastructure"],
      },
      {
        name: "algo surf",
        url: "https://algo.surf/",
        tags: ["algorand", "Blockchain Explorers", "D13"],
      },
      {
        name: "blockstalker",
        url: "https://blockstalker.io/",
        tags: ["algorand", "Blockchain Explorers"],
      },
      {
        name: "Lora",
        url: "https://lora.algokit.io/mainnet",
        tags: ["algorand", "Blockchain Explorers"],
      },
      {
        name: "algo3d",
        url: "https://algo3d.live/",
        tags: ["algorand", "Blockchain Explorers"],
      },
      {
        name: "algorand-ballet",
        url: "https://alexisrondeau.me/algorand-ballet/",
        tags: ["algorand", "Blockchain Explorers"],
      },
      {
        name: "dexscreener",
        url: "https://dexscreener.com/algorand",
        tags: ["algorand", "Blockchain Explorers"],
      },
      {
        name: "bitquery",
        url: "https://explorer.bitquery.io/algorand",
        tags: ["algorand", "Blockchain Explorers", "Infrastructure"],
      },
      {
        name: "allo.info",
        url: "https://allo.info/",
        tags: ["algorand", "Blockchain Explorers", "Infrastructure"],
      },
    ],
  },
  {
    category: "Wallets",
    icon: "./icons/wallet.png",
    links: [
      {
        name: "pera",
        url: "https://perawallet.app/",
        tags: [
          "dapps",
          "Wallets",
          "Official",
          "Defi",
          "dex aggregator",
          "yield farming",
          "Self-Custody",
          "trade",
          "swap",
          "Mobile",
          "payments",
        ],
      },
      {
        name: "defly",
        url: "https://defly.app/",
        tags: [
          "dapps",
          "Wallets",
          "Defi",
          "dex aggregator",
          "yield farming",
          "Self-Custody",
          "trade",
          "swap",
          "Mobile",
        ],
      },
      {
        name: "daffione",
        url: "https://www.daffione.com/",
        tags: ["dapps", "Wallets", "Self-Custody", "Desktop"],
      },
      {
        name: "lute",
        url: "https://lute.app/",
        tags: ["dapps", "Wallets", "Self-Custody", "Desktop"],
      },
      {
        name: "exodus",
        url: "http://exodus.com/",
        tags: [
          "Wallets",
          "dex",
          "Self-Custody",
          "trade",
          "swap",
          "Mobile",
          "Desktop",
        ],
      },
      {
        name: "zypto",
        url: "https://zypto.com/",
        tags: ["Wallets", "dex", "Self-Custody", "trade", "swap", "Mobile"],
      },
      {
        name: "ledger",
        url: "https://www.ledger.com/",
        tags: ["Hardware Wallets", "Self-Custody"],
      },
      {
        name: "a-wallet",
        url: "https://a-wallet.net/",
        tags: ["dapps", "Wallets", "Self-Custody", "Desktop"],
      },
    ],
  },
  {
    category: "Charts / Trackers",
    icon: "./icons/chart.png",
    links: [
      {
        name: "vestige",
        url: "http://vestige.fi/",
        tags: [
          "dapps",
          "Defi",
          "Finance",
          "Charts",
          "Trackers",
          "dex",
          "aggregator",
          "Infrastructure",
          "trade",
          "swap",
        ],
      },
      {
        name: "asastats",
        url: "http://asastats.com/",
        tags: ["dapps", "Charts", "portfolio", "Trackers", "Infrastructure"],
      },
      {
        name: "coinglass",
        url: "https://www.coinglass.com/currencies/ALGO",
        tags: [
          "Charts",
          "Trackers",
          "Derivatives",
          "Data Analysis",
          "liquidation",
          "long",
          "short",
          "positions",
        ],
      },
      {
        name: "coingecko",
        url: "https://www.coingecko.com/",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "defillama",
        url: "https://defillama.com/chain/Algorand",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "coinmarketcap",
        url: "https://coinmarketcap.com/",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "tradingview",
        url: "https://www.tradingview.com/",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "theblock",
        url: "https://www.theblock.co/prices?range=ALL",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "lookintobitcoin",
        url: "https://www.lookintobitcoin.com/",
        tags: ["Charts", "Trackers"],
      },
      {
        name: "algorandstats",
        url: "http://algorandstats.com/",
        tags: ["Charts", "Trackers", "Governance"],
        note: "old info",
      },
    ],
  },
  {
    category: "Defi / Finance",
    icon: "./icons/defi.png",
    links: [
      {
        name: "folks finance",
        url: "https://folks.finance/",
        tags: [
          "Defi",
          "Finance",
          "dex aggregator",
          "yield farming",
          "borrow",
          "lending",
          "loan",
          "Liquid Governance",
          "trade",
          "swap",
          "Galgo",
          "Xalgo",
          "Cross Chain",
          "Xchain",
          "Staking",
          "Concenses",
          "GAlgo",
          "XAlgo",
        ],
      },
      {
        name: "app.folks.finance",
        url: "https://app.folks.finance/",
        tags: ["dapps"],
      },
      {
        name: "algorai finance",
        url: "https://algorai.finance/",
        tags: ["Defi", "Finance", "options", "yield farming"],
      },
      {
        name: "app.algorai.finance",
        url: "https://app.algorai.finance/",
        tags: ["dapps"],
      },
      {
        name: "c3 (shutdown)",
        url: "https://c3.io/",
        tags: ["Shutdown", "c3.io"],
      },
      {
        name: "silodefi (Testnet)",
        url: "https://www.silodefi.com/",
        tags: ["Defi", "Finance", "Testnet"],
      },
      {
        name: "cometa",
        url: "https://cometa.farm/",
        tags: [
          "Defi",
          "Finance",
          "yield farming",
          "ultrade",
          "meme",
          "shitcoins",
          "Single-sided liquidity",
        ],
      },
      {
        name: "app.cometa.farm",
        url: "https://app.cometa.farm/",
        tags: ["dapps"],
      },
      {
        name: "rug.ninja",
        url: "https://rug.ninja/",
        tags: [
          "dapps",
          "Defi",
          "Finance",
          "yield farming",
          "trading",
          "Minting",
          "meme",
          "shitcoins",
          "launchpad",
          "create a new token",
          "Vestage",
        ],
      },
      {
        name: "compX",
        url: "https://compx.io/",
        tags: [
          "Defi",
          "Finance",
          "dex aggregator",
          "trade",
          "swap",
          "limit order",
          "yield farming",
          "stablecoin",
          "mint xUSD",
          "Portfolio Trackers",
          "swap",
          "defly",
          "alammex",
          "CDP Vaults",
          "Compx",
          "CAlgo",
          "Liquid Staking",
          "Consensus rewards",
        ],
      },
      {
        name: "app.compx",
        url: "https://app.compx.io/farms",
        tags: ["dapps"],
      },
    ],
  },
  {
    category: "DeFi / Minting / Bridges",
    icon: "./icons/bridge.png",
    links: [
      {
        name: "messina one",
        url: "https://messina.one/",
        tags: [
          "Defi",
          "Finance",
          "Minting",
          "Bridges",
          "Liquid",
          "Governance",
          "Malgo",
          "staking",
          "Bridge",
        ],
      },
      {
        name: "algomint",
        url: "http://algomint.io/",
        tags: [
          "Defi",
          "Finance",
          "Minting",
          "Stablecoins",
          "GOUSD",
          "USA",
          "RWA",
          "real world assets",
          "goUSD",
          "xUSD",
          "GoBTC",
          "GoETH",
          "goMINT",
          "Bridge",
        ],
      },
      {
        name: "app.algomint",
        url: "https://app.algomint.io/",
        tags: ["dapps"],
      },
      {
        name: "basket.algomint",
        url: "https://basket.algomint.io/",
        tags: ["dapps"],
      },
      {
        name: "p.network",
        url: "https://p.network/",
        tags: ["Defi", "Finance", "Minting", "Bridges", "pbtc", "PNT"],
      },
      {
        name: "wormhole",
        url: "https://wormhole.com/",
        tags: [
          "Defi",
          "Finance",
          "Minting",
          "Bridges",
          "Wtokens",
          "AVM",
          "EVM",
        ],
      },
      {
        name: "londonbridge",
        url: "https://londonbridge.io/",
        tags: [
          "Defi",
          "Finance",
          "Minting",
          "Bridges",
          "AVM",
          "EVM",
          "Algorand and Ethereum",
        ],
      },
      {
        name: "deflex",
        url: "https://www.deflex.fi/",
        tags: [
          "Defi",
          "Finance",
          "dex aggregator",
          "dev tools",
          "Defly",
          "Alammex",
        ],
      },
      {
        name: "aramid finance",
        url: "https://www.aramid.finance/",
        tags: [
          "Defi",
          "Finance",
          "bridge",
          "AVM",
          "Voi",
          "Algorand",
          "EVM",
          "Arbitrum",
          "Base",
        ],
      },
    ],
  },
  {
    category: "DeX / AMM",
    icon: "./icons/swap.png",
    links: [
      {
        name: "vestige",
        url: "http://vestige.fi/",
        tags: [
          "dapps",
          "Defi",
          "Finance",
          "Charts",
          "Trackers",
          "dex aggregator",
          "Infrastructure",
          "trade",
          "swap",
          "meme",
          "shitcoins",
        ],
      },
      {
        name: "pact",
        url: "http://pact.fi/",
        tags: [
          "Defi",
          "Finance",
          "AMM",
          "dex aggregator",
          "yield farming",
          "trade",
          "swap",
          "humble",
          "Liquid Staking",
          "Consensus",
          "rewards",
        ],
      },
      {
        name: "app.pact.fi",
        url: "https://app.pact.fi/swap",
        tags: ["dapps"],
      },
      {
        name: "tinyman",
        url: "http://tinyman.org/",
        tags: [
          "Defi",
          "Finance",
          "AMM",
          "dex",
          "yield farming",
          "trade",
          "swap",
          "TAlgo",
          "Liquid Staking",
          "Consensus",
          "rewards",
        ],
      },
      {
        name: "app.tinyman",
        url: "https://app.tinyman.org/#/swap?asset_in=0&asset_out=31566704",
        tags: ["dapps"],
      },
      {
        name: "app.humble (Shutdown)",
        url: "http://app.humble.sh/",
        tags: ["humble"],
      },
      {
        name: "ultrade(Testnet)",
        url: "https://ultrade.org/",
        tags: ["Defi", "Finance", "trade", "swap"],
      },
      /* {
        name: "althena(This site can’t be reached)",
        url: "https://www.althena.io/",
        tags: ["Defi", "Finance", "dex aggregator", "trade", "swap"],
      }, */

      /*  {
        name: "algodex (Error 1000 site unavailable 10/19/24)",
        url: "http://about.algodex.com/",
        tags: ["Defi", "Finance", "trade", "swap"],
      }, */
      {
        name: "alammex (shut down)",
        url: "https://www.alammex.com/",
        tags: [
          "Defi",
          "Finance",
          "dex aggregator",
          "limit order",
          "trade",
          "swap",
          "compx.io",
        ],
      },
      {
        name: "coop",
        url: "https://vestige.fi/asset/796425061",
        tags: ["coop"],
      },
      {
        name: "Bartle Doo",
        url: "https://vestige.fi/asset/829992960",
        tags: ["Bartle Doo"],
      },
      {
        name: "Orange",
        url: "https://vestige.fi/asset/1284444444",
        tags: ["Orange"],
      },
    ],
  },

  {
    category: "NFT / Apps + Support",
    icon: "./icons/nft.png",
    links: [
      {
        name: "asalytic",
        url: "https://www.asalytic.app/",
        tags: ["dapps", "NFTexplorer", "marketplace"],
      },
      {
        name: "highforge",
        url: "https://highforge.io/",
        tags: ["dapps", "NFT Launch"],
      },
      {
        name: "minthol",
        url: "https://www.minthol.art/",
        tags: ["dapps", "NFT"],
      },
      {
        name: "NFDomains",
        url: "https://nf.domains/",
        tags: [
          "dapps",
          "NFT",
          "Algorand",
          "name service",
          "marketplace",
          "Non-Fungible Domains",
          "readable identities",
          "wallet",
          "NFD",
        ],
      },
      {
        name: "atomixwap",
        url: "https://atomixwap.xyz/",
        tags: ["dapps", "NFT", "marketplace", "trade", "swap"],
      },
      {
        name: "Bartle Doo Derp Squad",
        url: "https://www.asalytic.app/collection/bartle-doo-derp-squad?tab=market&traitTypes=&traitValues=&filterTypes=&filterValues=",
        tags: ["Bartle Doo Derp Squad"],
        hidden: true,
      },
    ],
  },
  {
    category: "NFT / Auction / Markets",
    icon: "./icons/nft.png",
    links: [
      {
        name: "Algoxnft",
        url: "http://algoxnft.com/",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "Exa Market",
        url: "https://exa.market/",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "Rand Gallery",
        url: "http://randgallery.com/",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "algogems",
        url: "http://algogems.io/",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "Rxelms",
        url: "https://rxelms.com/marketplace",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "shufl",
        url: "https://shufl.app/",
        tags: ["dapps", "NFT", "marketplace", "Shuffles"],
      },
      {
        name: "dartroom",
        url: "https://dartroom.xyz/overview",
        tags: ["NFT", "marketplace", "Auctions"],
      },
      {
        name: "rafflebees",
        url: "https://www.rafflebees.com/",
        tags: ["dapps", "NFT", "marketplace", "Auctions", "Shuffles"],
      },
      {
        name: "Fifa Collect",
        url: "https://collect.fifa.com/",
        tags: ["Football", "Soccer", "FIFA", "NFTs"],
      },
    ],
  },
  {
    category: "NFT / Music / Video",
    icon: "./icons/music.png",
    links: [
      {
        name: "aurally",
        url: "https://aurally.xyz/",
        tags: ["music", "streaming", "Video", "NFT"],
      },
      {
        name: "anotemusic",
        url: "https://www.anotemusic.com/",
        tags: ["Music"],
      },
      {
        name: "book.io",
        url: "https://app.book.io/bookshelf",
        tags: ["books", "reading"],
      },
      {
        name: "opulous (Beta)",
        url: "https://app.opulous.org/login",
        tags: ["Music"],
      },
      { name: "xfinite", url: "http://xfinite.io/", tags: ["Video"] },
    ],
  },
  {
    category: "Dev / Infrastructure",
    icon: "./icons/code.png",
    links: [
      {
        name: "Algorand devs",
        url: "https://developer.algorand.co/",
        tags: [
          "Dev Tools",
          "Dev Infrastructure",
          "Official",
          "algorand foundation",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "algokit-cli",
        url: "https://github.com/algorandfoundation/algokit-cli",
        tags: [
          "Dev Tools",
          "Dev Infrastructure",
          "Official",
          "algorand foundation",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "Teal Docs",
        url: "https://tealish.readthedocs.io/",
        tags: [
          "Dev Infrastructure",
          "Dev Tools",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "hipolabs",
        url: "https://hipolabs.com/",
        tags: [
          "Dev Infrastructure",
          "Dev Tools",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "reach",
        url: "http://reach.sh/",
        tags: [
          "Dev Infrastructure",
          "Dev Tools",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "appliedblockchain",
        url: "https://appliedblockchain.com/",
        tags: [
          "Dev Infrastructure",
          "Dev Tools",
          "developer suite",
          "asset manager",
        ],
      },
    ],
  },
  {
    category: "Dev Tools",
    icon: "./icons/devtools.png",
    links: [
      {
        name: "algorand github",
        url: "http://github.com/algorand",
        tags: [
          "Dev Tools",
          "Official",
          "algorand foundation",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "txnduck",
        url: "https://txnduck.vercel.app/en",
        tags: [
          "dapps",
          "Dev Tools",
          "sign transactions",
          "payment",
          "developer suite",
          "asset manager",
        ],
      },
      {
        name: "algotools",
        url: "https://algotools.org/",
        tags: [
          "dapps",
          "Dev Tools",
          "sign transactions",
          "payment",
          "developer suite",
          "asset manager",
        ],
      },
      {
        name: "algosafe",
        url: "https://algosafe.io/",
        tags: [
          "Dev Tools",
          "Multi-Sig",
          "signature",
          "sign transactions",
          "Digital Asset Safe",
          "payment",
          "developer suite",
          "asset manager",
          "app manager",
        ],
      },
      {
        name: "subtopia",
        url: "https://subtopia.io/",
        tags: [
          "dapps",
          "Dev Tools",
          "Decentralized subscription management",
          "sign transactions",
          "payment",
          "developer suite",
          "asset manager",
        ],
      },
      {
        name: "ztlment",
        url: "https://ztlment.com/",
        tags: [
          "Dev Tools",
          "developer suite",
          "asset manager",
          "compliant escrow wallet infrastructure",
          "online platforms",
          "marketplaces",
          "ledger technology",
          "Regulated",
          "PSD2",
          "Denmark",
        ],
      },
      {
        name: "wallet.wen.tools",
        url: "https://wallet.wen.tools/",
        tags: [
          "dapps",
          "NFT",
          "Dev Tools",
          "sign transactions",
          "payment",
          "developer suite",
          "asset manager",
          "we.thurstober",
          "labs.thurstober",
          "wallet",
        ],
      },
      {
        name: "wen.tools",
        url: "https://www.wen.tools/",
        tags: [
          "dapps",
          "NFT",
          "Dev Tools",
          "sign transactions",
          "payment",
          "developer suite",
          "asset manager",
          "we.thurstober",
          "labs.thurstober",
        ],
      },
    ],
  },

  {
    category: "Aggregation Hub",
    icon: "./icons/hub.png",
    links: [
      {
        name: "Algorand Eco",
        url: "https://algorand.co/ecosystem/overview",
        tags: [
          "community Hub",
          "Official",
          "DIRECTORY",
          "ecosystem.algorand.com",
          "Foundation",
          "inc",
        ],
      },
      {
        name: "algodirectory",
        url: "https://algodirectory.app/",
        tags: [
          "dapps",
          "on-chain directory",
          "Algorand ecosystem",
          "community Hub",
          "DIRECTORY",
          "SilentRhetoric.algo",
        ],
      },
      {
        name: "awesomealgo",
        url: "https://awesomealgo.com/",
        tags: ["community Hub", "DIRECTORY"],
      },
      {
        name: "algotables",
        url: "https://algotables.github.io/",
        tags: ["community Hub", "algorand", "DIRECTORY"],
      },
      {
        name: "algorandlinks",
        url: "https://app.nf.domains/name/algorandlinks.algo",
        tags: ["community Hub", "algorand", "DIRECTORY"],
      },
      {
        name: "Algonauts Official Discord",
        url: "https://algonauts.io/",
        tags: ["community Hub", "algorand", "DIRECTORY"],
      },
      {
        name: "AlgoFam Algonauts & Randos",
        url: "https://x.com/i/lists/1674779248643690497",
        tags: [
          "community Hub",
          "News",
          "Media",
          "Latest",
          "Algorand",
          "Algo",
          "X",
          "DIRECTORY",
        ],
      },
    ],
  },
  {
    category: "Airdrops / Faucets",
    icon: "./icons/drop.png",
    links: [
      {
        name: "Testnet Dispenser",
        url: "https://bank.testnet.algorand.network/",
        tags: ["Dev Tools", "Airdrops", "Faucets", "Official"],
      },
      {
        name: "Testnet Dispenser 2",
        url: "https://dispenser.testnet.aws.algodev.network/",
        tags: ["Dev Tools", "Airdrops", "Faucets"],
      },
      {
        name: "freckletoken",
        url: "https://www.freckletoken.com/",
        tags: ["Dev Tools", "Airdrops", "Faucets"],
      },
      {
        name: "viewreward",
        url: "https://www.viewreward.app/",
        tags: ["Dev Tools", "Airdrops", "Faucets"],
      },
    ],
  },

  {
    category: "News / Media",
    icon: "./icons/news.png",
    links: [
      {
        name: "Twitter News",
        url: "https://x.com/i/lists/1674779248643690497",
        tags: [
          "Hub News",
          "Media",
          "Latest",
          "Algorand",
          "Algo X",
          "Twitter List",
          "AlgoFam",
          "Algonauts",
          "Randos",
        ],
      },
      {
        name: "Algorand Forum",
        url: "https://forum.algorand.org/top",
        tags: ["News", "Media", "Official", "Algorand Foundation"],
      },
      {
        name: "algonaut",
        url: "https://algonaut.space/",
        tags: ["News", "Media", "Algorand"],
      },
      {
        name: "algodaddy",
        url: "https://www.algodaddy.org/",
        tags: ["News", "Media", "Algorand"],
      },
      {
        name: "algocleanup",
        url: "https://algocleanup.com/blog",
        tags: ["News", "Media", "Algorand"],
      },
      {
        name: "d13",
        url: "https://d13.co/",
        tags: ["News", "Media"],
      },
    ],
  },
  {
    category: "Real Estate / Travel / RWA",
    icon: "./icons/estate.png",
    links: [
      {
        name: "lofty",
        url: "http://lofty.ai/",
        tags: [
          "RWA",
          "Real World Assets",
          "Real Estate",
          "DeFi",
          "Yield Farming",
        ],
      },
      {
        name: "pocketpropertiesapp",
        url: "http://pocketpropertiesapp.com/",
        tags: ["RWA", "Real World Assets", "Real Estate"],
      },
      {
        name: "vestaequity",
        url: "http://vestaequity.net/",
        tags: [
          "RWA",
          "Real World Assets",
          "Real Estate",
          "Unlocks Real Estate Equity",
          "Homeowners",
          "Investors",
          "Trade",
          "Fractionalized Ownership",
        ],
      },
      {
        name: "meld gold",
        url: "https://www.meld.gold/",
        tags: [
          "RWA",
          "Real World Assets",
          "DeFi",
          "GOLD$",
          "SILVER$",
          "PLAT",
          "PALD",
          "goMINT",
          "goEth",
          "goBTC",
        ],
      },
      {
        name: "asknimblr",
        url: "https://asknimblr.com/",
        tags: ["Insurance", "Alternative Asset", "Nimblr.insure"],
      },
      {
        name: "daybyday",
        url: "https://app.daybyday.io/",
        tags: ["Dapps"],
        hidden: true,
      },
      {
        name: "climatetrade",
        url: "https://climatetrade.com/",
        tags: [
          "RWA",
          "Real World Assets",
          "Marketplace",
          "Trading",
          "Carbon Credits",
          "Climate Change",
        ],
      },
      {
        name: "travelX",
        url: "https://www.travelx.io/",
        tags: [
          "RWA",
          "Real World Assets",
          "Airline Tickets",
          "Alternative Asset",
          "Plane",
        ],
      },
      {
        name: "quantoz",
        url: "https://quantoz.com/",
        tags: ["RWA", "Real World Assets", "EURO", "EURD", "Stablecoins"],
      },
      {
        name: "eurs.stasis",
        url: "https://eurs.stasis.net/",
        tags: [
          "RWA",
          "Real World Assets",
          "EURO",
          "EURS",
          "Stablecoins",
          "CBDC",
        ],
      },
      {
        name: "circle",
        url: "https://www.circle.com/blog/ushering-in-the-next-chapter-for-usdc",
        tags: [
          "RWA",
          "Real World Assets",
          "USD",
          "USA",
          "Stablecoins",
          "USDCa",
        ],
      },
      {
        name: "agrotoken",
        url: "https://www.agrotoken.com/en/home",
        tags: [
          "RWA",
          "Real World Assets",
          "Agricultural Commodities",
          "Tokenization",
          "Alternative Asset",
          "AGRO",
          "Farmers",
          "Grain",
        ],
      },
    ],
  },
  {
    category: "Proof of Data / Utility / Tools",
    icon: "./icons/tools.png",
    links: [
      {
        name: "pop.allo",
        url: "https://pop.allo.info/",
        tags: ["dapps", "Proof of Data"],
      },
      {
        name: "gora",
        url: "https://www.gora.io/",
        tags: ["Proof of Data", "Oracles", "Bridges"],
      },
      {
        name: "licitdoc",
        url: "http://licitdoc.com/",
        tags: ["Proof of Data"],
      },
      {
        name: "algoscout",
        url: "http://algoscout.net/",
        tags: ["Proof of Data"],
      },
      {
        name: "Data History Museum",
        url: "https://museum.datahistory.org/",
        tags: [
          "Proof of Data",
          "History",
          "Museum",
          "Historical Events",
          "Earthquakes",
          "Solar Flares",
        ],
      },
      {
        name: "goplausible",
        url: "https://goplausible.com/",
        tags: ["Proof of Data", "Infrastructure", "thisdid"],
      },
      {
        name: "goplausible app",
        url: "https://goplausible.xyz/",
        tags: ["dapps"],
      },
      {
        name: "thisdid",
        url: "https://thisdid.com/",
        tags: [
          "dapps",
          "Proof of Data",
          "Infrastructure",
          "Universal Decentralized Identifier (DID)",
          "Resolver ID",
          "goplausible.com",
        ],
      },
      {
        name: "folksfeed",
        url: "https://www.folksfeed.io/",
        tags: ["Proof of Data", "Oracles"],
      },
      {
        name: "Pera Governance",
        url: "https://governance.perawallet.app/",
        tags: ["dapps", "Proof of Data"],
      },
    ],
  },
  {
    category: "Utility",
    icon: "./icons/adjustments.png",
    links: [
      {
        name: "wecoop.xyz",
        url: "https://wecoop.xyz/",
        tags: [
          "dapps",
          "Infrastructure",
          "social media",
          "recoop",
          "YouTube",
          "News",
          "Media",
          "Algorand",
          "reddit",
          "web3",
          "public messaging",
          "CoopCoin",
          "$COOP",
          "meme",
        ],
      },
      {
        name: "clerk.algo.surf",
        url: "https://clerk.algo.surf/",
        tags: [
          "utility",
          "Dev",
          "Infrastructure",
          "Dev Tools",
          "developer",
          "Algorand",
          "CSV Export",
          "account",
          "ALGO",
          "ASA",
          "transactions",
        ],
      },
      {
        name: "NFTDiscordPal",
        url: "https://linktr.ee/NFTDiscordPal",
        tags: [],
      },
      {
        name: "algofame",
        url: "https://linktr.ee/algofame",
        tags: [
          "FAME",
          "Fam",
          "farmers",
          "Bilal",
          "Food",
          "Autonomy",
          "Agriculture",
          "food",
        ],
      },
      {
        name: "algovanity",
        url: "https://algovanity.com/",
        tags: ["custom", "readable", "named wallet"],
      },
      {
        name: "metapost",
        url: "https://metapost.io/",
        tags: ["dapps", "reddit", "web3", "public messaging"],
      },
      {
        name: "fairinbox",
        url: "https://fairinbox.io/",
        tags: ["email", "messaging", "web3 messaging"],
      },
      {
        name: "notiboy",
        url: "https://notiboy.com/",
        tags: ["email", "messaging", "web3 messaging"],
      },
      {
        name: "akita community",
        url: "https://akita.community/",
        tags: [
          "dapps",
          "Infrastructure",
          "social media",
          "News",
          "Media",
          "Algorand",
          "reddit",
          "web3",
          "public messaging",
          "$akita",
          "meme",
        ],
      },
      {
        name: "marketcapof",
        url: "https://marketcapof.com/algorand/ethereum/",
        tags: [
          "Show the price of Algo with the market cap of crypto",
          "roi calculator",
        ],
      },
      {
        name: "weusealgorand",
        url: "https://weusealgorand.net/",
        tags: ["How long have you been using Algorand?"],
      },
    ],
  },
  {
    category: "eCommerce Integration",
    icon: "./icons/ecommerce.png",
    links: [
      {
        name: "hesab.com",
        url: "https://hesab.com/",
        tags: [
          "HesabPay",
          "Digital Payments Platform in Afghanistan",
          "International payments",
          "Digital payments",
          "humanitarian aid",
        ],
      },
      {
        name: "alright",
        url: "https://alright.app/",
        tags: ["Digital payments", "trade"],
      },
      {
        name: "suave money",
        url: "https://suave.money/",
        tags: ["Digital payments", "trade", "Accept Crypto From Any Chain"],
      },
      {
        name: "koibanx",
        url: "https://koibanx.com/",
        tags: [
          "Digital payments",
          "trade",
          "Accept Crypto From Any Chain",
          "Provides blockchain solutions",
          "tokenizing assets",
          "securing payment transactions",
          "BANKING INFRASTRUCTURE IN LATAM",
        ],
      },
      {
        name: "ctrl-alt",
        url: "https://www.ctrl-alt.co/",
        tags: [
          "Digital payments",
          "trade",
          "B2B platform",
          "private equity businesses",
          "Digital Asset Wrapping",
        ],
      },
    ],
  },
  {
    category: "Gaming / Betting",
    icon: "./icons/slot.png",
    links: [
      {
        name: "algo-casino",
        url: "http://algo-casino.com/",
        tags: ["Gaming", "Betting", "gambling"],
      },
      {
        name: "smartpoker",
        url: "https://smartpoker.io/",
        tags: ["Gaming", "Betting", "gambling"],
      },
      {
        name: "algobets netlify",
        url: "https://algobets.netlify.app/",
        tags: ["Gaming", "Betting", "gambling"],
      },
      {
        name: "lottorace",
        url: "https://www.lottorace.cloud/",
        tags: ["dapps", "Gaming", "Betting", "gambling"],
      },
      {
        name: "algotard.io",
        url: "https://algotard.io/",
        tags: [
          "dapps",
          "Gaming",
          "Betting",
          "gambling",
          "Tardly",
          "No-Loss Lottery",
          "NLL",
          "Scott Summers",
          "Algotardio",
          "$ATARD",
          "Yieldly",
        ],
      },
      {
        name: "Alpha Arcade",
        url: "https://www.alphaarcade.com/",
        tags: ["dapps", "Gaming", "Betting", "gambling", "prediction market"],
      },
    ],
  },
  {
    category: "Gaming / P2E",
    icon: "./icons/console.png",
    links: [
      {
        name: "Astro Explorer",
        url: "https://astroexplorer.co/",
        tags: ["Gaming", "P2E", "Retro Arcade", "Bork Bork Zerker"],
      },
      {
        name: "fracctal monsters",
        url: "https://fracctalmonstersnft.com/home",
        tags: ["Gaming"],
      },
      {
        name: "cosmic champs",
        url: "http://cosmicchamps.com/",
        tags: ["Gaming"],
      },
      {
        name: "hexlands",
        url: "https://hexlands.paimastudios.com/",
        tags: ["Gaming"],
      },
      {
        name: "ghettopigeon warzones",
        url: "https://warzones.ghettopigeon.com/",
        tags: ["Gaming"],
      },
    ],
  },
  {
    category: "Misc",
    icon: "./icons/cubes.png",
    links: [
      {
        name: "brave",
        url: "https://brave.com/",
        tags: ["web browser", "internet"],
      },
      {
        name: "presearch",
        url: "https://presearch.com/",
        tags: ["google"],
      },
      {
        name: "proton",
        url: "https://proton.me/",
        tags: ["email"],
      },
      {
        name: "chat.openai",
        url: "https://chat.openai.com/",
        tags: ["chat GPT", "chatGPT"],
      },
      {
        name: "chainui",
        url: "https://chainui.com/",
        tags: [],
      },
      {
        name: "nft.storage",
        url: "https://nft.storage/",
        tags: [],
      },
    ],
  },
  {
    category: "Node Info & Guides",
    icon: "./icons/nodes.png",
    links: [
      {
        name: "run-a-node (Linux)",
        url: "https://developer.algorand.org/docs/run-a-node/setup/types/",
        tags: ["node", "official", "tools", "guides"],
      },
      {
        name: "AF (Linux)",
        url: "https://github.com/algorandfoundation/algorun",
        tags: ["node", "official", "tools", "guides"],
      },
      {
        name: "nodekit.run (Linux)",
        url: "https://nodekit.run/",
        tags: ["node", "official", "tools", "guides", "algorandfundation"],
      },
      {
        name: "AlloCtrl (Linux)",
        url: "https://github.com/AlgoNode/alloctrl",
        tags: ["node", "tools", "guides", "infrastructure"],
      },
      {
        name: "nodeguide (Ubuntu)",
        url: "https://django-xyz.github.io/node/",
        tags: ["node", "tools", "guides"],
      },
      {
        name: "algorand observer",
        url: "https://consensus.algorand.observer/",
        tags: [
          "node",
          "tools",
          "guides",
          "infrastructure",
          "D13",
          "Algorand",
          "consensus",
          "Participation",
          "Data",
        ],
      },
      {
        name: "Block Stalker",
        url: "https://github.com/BlockStalker/algorand-undoc-docs",
        tags: ["node", "tools", "guides"],
      },
      {
        name: "One Click Node (Windows)",
        url: "https://github.com/AustP/austs-one-click-node",
        tags: ["node", "tools", "guides", "AustP", "austs", "oneclick", "node"],
      },
      {
        name: "GalaxyPay/func (Windows)",
        url: "https://github.com/GalaxyPay/func",
        tags: ["node", "tools", "guides", "Lute", "avm", "oneclick", "node"],
      },
    ],
  },
  {
    category: "Node Tools & Resources",
    icon: "./icons/nodes.png",
    links: [
      {
        name: "Reti",
        url: "https://reti.nodely.io/",
        tags: [
          "dapps",
          "node",
          "tools",
          "guides",
          "yield",
          "farming",
          "pool",
          "stake",
          "concensus",
          "delegation",
        ],
      },
      {
        name: "myth finance",
        url: "https://myth.finance/",
        tags: [
          "dapps",
          "node",
          "tools",
          "guides",
          "yield",
          "farming",
          "pool",
          "stake",
          "concensus",
          "delegation",
          "dualSTAKE",
          "D13",
        ],
      },
      {
        name: "Valar",
        url: "https://igoprotect.vercel.app/",
        tags: [
          "dapps",
          "node",
          "tools",
          "guides",
          "yield",
          "farming",
          "pool",
          "stake",
          "concensus",
          "delegation",
          "valar",
          "peer",
        ],
      },
      {
        name: "nodely",
        url: "https://g.nodely.io/d/consensus/consensus?orgId=1&from=now-24h&to=now&timezone=browser&var-top20range=24&var-addresses=%25",
        tags: ["indexer", "node", "tools", "api", "ipfs", "public"],
      },
      {
        name: "blocki",
        url: "https://www.blocki.app/",
        tags: ["node", "tools", "guides"],
      },
      {
        name: "Algo Desktop Wallpaper",
        url: "https://drive.proton.me/urls/SKJTCSTN18#v9Nlg1bingFM",
        tags: ["jpg", "pic", " png"],
      },
      {
        name: "Algo Mobile Wallpaper",
        url: "https://drive.proton.me/urls/2GXP3BKP48#PavCVXvFH3xE",
        tags: ["jpg", "pic", " png"],
      },
      {
        name: "Algorand Museum",
        url: "https://drive.proton.me/urls/0REETAP5RM#7baRBx8Wk71K",
        tags: [
          "white",
          "paper",
          "byzantine",
          "theoretical",
          "Jing",
          "Chen",
          "Silvio",
          "Micali",
          "Sergey",
          "Gorbunov",
          "Georgios",
          "Vlachos",
        ],
      },
      {
        name: "artemis",
        url: "https://app.artemis.xyz/developer-activity?ecosystemValue=Algorand",
        tags: ["Developer", "activity", "commits", "active", "devs"],
      },
      {
        name: "algodevstats",
        url: "https://www.algodevstats.org/dashboard",
        tags: [
          "Developer",
          "activity",
          "commits",
          "active",
          "devs",
          "insights",
          "geos",
          "project",
          "types",
        ],
      },
      {
        name: "Silent Rhetoric",
        url: "https://gist.github.com/SilentRhetoric/b8bdddae38e3169cf0004f3a7e4b164b",
        tags: ["node", "tools", "guides", "nodechecks"],
      },
    ],
  },
  {
    category: "YouTube Squad",
    icon: "./icons/youtube.png",
    links: [
      {
        name: "The ReCoop",
        url: "https://www.youtube.com/c/TheReCoop",
        tags: ["Social Media", "YouTube", "News", "Media", "Algorand"],
      },
      {
        name: "Passive Income Network",
        url: "https://www.youtube.com/c/PassiveIncomeNetwork",
        tags: ["Social Media", "YouTube", "News", "Media", "Algorand"],
      },
      {
        name: "Algo HQ",
        url: "https://www.youtube.com/channel/UCEKO04lpmZpH848yoETCFDg",
        tags: ["Social Media", "YouTube", "News", "Media", "Algorand"],
      },
      {
        name: "Algorand",
        url: "http://youtube.com/algorand",
        tags: [
          "Social Media",
          "YouTube",
          "Official",
          "News",
          "Media",
          "Algorand",
        ],
      },
    ],
  },
  {
    category: "Social Media",
    icon: "./icons/social.png",
    links: [
      {
        name: "Algorand Discord",
        url: "https://discord.gg/Q5Wjdz3uHH",
        tags: ["Social Media", "Official", "News", "Media", "Algorand"],
      },
      {
        name: "Algorand LinkedIn",
        url: "http://linkedin.com/company/algorand",
        tags: ["Social Media", "Official", "Algorand", "linkedin"],
      },
      {
        name: "Algo Official Reddit",
        url: "https://www.reddit.com/r/AlgorandOfficial",
        tags: ["Social Media", "Official", "Algorand", "reddit"],
      },
      {
        name: "Algo Community Reddit",
        url: "https://www.reddit.com/r/algorand/",
        tags: ["Social Media", "reddit"],
      },
      {
        name: "x.com/Algorand",
        url: "https://x.com/Algorand",
        tags: [
          "Social Media",
          "Official",
          "algorandtechnologies.com",
          "twitter.com",
        ],
      },
      {
        name: "Algorand Foundation",
        url: "https://x.com/AlgoFoundation",
        tags: [
          "Social Media",
          "Official",
          "x",
          "twitter",
          "algorand.co",
          "twitter.com",
        ],
      },
      {
        name: "Algorand Telegram",
        url: "http://t.me/algorand",
        tags: ["Social Media", "Official", "telegram.org"],
      },
    ],
  },
];
